DROP DATABASE IF EXISTS streaming_bd;
CREATE DATABASE streaming_bd;
USE streaming_bd;

SET sql_safe_updates = 0 ;

CREATE TABLE FILME( 
ID INT PRIMARY KEY AUTO_INCREMENT,
TITULO VARCHAR (20) NOT NULL,
GENERO VARCHAR(30) NOT NULL,
ANO YEAR NOT NULL
);

ALTER TABLE FILME ADD CLASSIFICACAO  VARCHAR(10) NOT NULL;
ALTER TABLE FILME MODIFY TITULO VARCHAR(60);

INSERT INTO FILME (TITULO,GENERO,ANO,CLASSIFICACAO) VALUES ('UP altas aventuras ' ,'animacao', '2009','infantil');
INSERT INTO FILME (TITULO,GENERO,ANO,CLASSIFICACAO) VALUES ('101 Dalmatas ' ,'animacao/infantil', '1961','infantil');
INSERT INTO FILME (TITULO,GENERO,ANO,CLASSIFICACAO) VALUES ('Madagascar' ,'animacao/infantil/comedia', '2005','infantil');

DELETE FROM FILME WHERE ID=1;
SELECT *FROM FILME ;

SHOW TABLES;
TRUNCATE FILME ;
