CREATE DATABASE empresa;

CREATE TABLE empresa.Empregado
(
PNOME VARCHAR(15) NOT NULL,
MINICIAL CHAR,
UNOME VARCHAR(15)   , 
SSN BIGINT NOT NULL   ,
DATANASC DATE ,
DENDERECO VARCHAR (80),
SEXO BIT ,
SALARIO DECIMAL(10,2),
SSN_SUPERVISOR BIGINT ,
DNUMERO_DEPARTAMENTO INTEGER NOT NULL DEFAULT 1   ,

PRIMARY KEY (SSN),
FOREIGN KEY (SSN_SUPERVISOR) REFERENCES empresa.Empregado (SSN)  ON DELETE SET  NULL ON UPDATE CASCADE
);
 

CREATE TABLE empresa.Departamento(
DNOME VARCHAR(15),
DNUMERO INTEGER NOT NULL DEFAULT 1 ,
SSN_EMPREGADO BIGINT  ,
DATAINICIO DATE ,

PRIMARY KEY (DNUMERO),
FOREIGN KEY (SSN_EMPREGADO) REFERENCES empresa.Empregado (SSN) ON  DELETE SET NULL ON UPDATE CASCADE 
);  

INSERT INTO empresa.Departamento (DNOME) VALUES ('Dep_padrao'); 
INSERT empresa.Empregado(PNOME,SSN) VALUES ('GERENTE_PADRAO',1);

ALTER TABLE empresa.Empregado ADD FOREIGN KEY(DNUMERO_DEPARTAMENTO) REFERENCES empresa.Departamento(DNUMERO) ON DELETE SET DEFAULT ON UPDATE CASCADE;
 
CREATE TABLE empresa.Projeto (
PNOME VARCHAR(15),
PNUMERO  INTEGER NOT NULL ,
PLOCALIZACAO VARCHAR(20),
DNUMERO_DEPARTAMENTO INTEGER NOT NULL,

PRIMARY KEY (PNUMERO),
FOREIGN KEY (DNUMERO_DEPARTAMENTO) REFERENCES empresa.Departamento (DNUMERO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE empresa.Dependente(
SSN_EMPREGADO BIGINT NOT NULL ,
NOME_DEPENDENTE VARCHAR(15) ,
SEXO BIT ,
DATANASC DATE NOT NULL ,
PARENTESCO VARCHAR(15) NOT NULL,

PRIMARY KEY(SSN_EMPREGADO,NOME_DEPENDENTE),
FOREIGN KEY (SSN_EMPREGADO) REFERENCES empresa.Empregado (SSN) ON DELETE CASCADE ON UPDATE CASCADE 
);

CREATE TABLE empresa.Deptolocais(
LNUMERO BIGINT NOT NULL ,
DLOCALIZACAO VARCHAR(15) NOT NULL,
DNUMERO_DEPARTAMENTO INTEGER NOT NULL ,

PRIMARY KEY (LNUMERO),
FOREIGN KEY (DNUMERO_DEPARTAMENTO) REFERENCES empresa.Departamento (DNUMERO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE empresa.trabalhaem(
SSN_EMPREGADO BIGINT NOT NULL,
PNUMERO_PROJETO INTEGER NOT NULL  ,
HORAS DECIMAL (4,2) ,

PRIMARY KEY (SSN_EMPREGADO,PNUMERO_PROJETO),
FOREIGN KEY (SSN_EMPREGADO) REFERENCES empresa.Empregado (SSN) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (PNUMERO_PROJETO) REFERENCES empresa.Projeto (PNUMERO) ON DELETE CASCADE ON UPDATE CASCADE
);
