CREATE DATABASE banco;
USE banco;

CREATE TABLE conta(
NUMERO INT NOT NULL,
SALDO DECIMAL(15,2),
DATA_ACESO DATE,

PRIMARY KEY (NUMERO)
);

CREATE TABLE agencia(
NUMERO INT NOT NULL,
NOME VARCHAR(15),
CIDADE VARCHAR(15),
FUNDOS DECIMAL(15,2) ,

PRIMARY KEY (NUMERO)
);

CREATE TABLE poupanca(
NUMERO_CONTA INT NOT NULL,
TAXA DECIMAL(15,2),

PRIMARY KEY(NUMERO_CONTA),
FOREIGN KEY(NUMERO_CONTA) REFERENCES conta (NUMERO) ON DELETE CASCADE  ON UPDATE CASCADE
);

CREATE TABLE movimento(
NUMERO_CONTA INT NOT NULL,
LIMITE DECIMAL(15,2) ,

PRIMARY KEY(NUMERO_CONTA),
FOREIGN KEY(NUMERO_CONTA) REFERENCES conta (NUMERO) ON DELETE CASCADE  ON UPDATE CASCADE
);

CREATE TABLE bancario(
SSN INT NOT NULL,
NOME VARCHAR(15),
TELEFONE VARCHAR(20),
DATA_CONTRATACAO DATE NOT NULL ,
SSN_GERENTE_BANCARIO INT ,

PRIMARY KEY (SSN) ,
FOREIGN KEY (SSN_GERENTE_BANCARIO) REFERENCES bancario(SSN) ON DELETE SET NULL ON UPDATE CASCADE 
);

CREATE TABLE cliente(
SSN INT NOT NULL,
NOME VARCHAR(15),
RUA VARCHAR(15),
CIDADE VARCHAR(15),
SSN_AGENTE_BANCARIO INT ,

PRIMARY KEY (SSN),
FOREIGN KEY (SSN_AGENTE_BANCARIO) REFERENCES bancario ( SSN) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE posse (
	SSN_CLIENTE INT NOT NULL,
    NUMERO_CONTA INT NOT NULL,
    PRIMARY KEY(SSN_CLIENTE,NUMERO_CONTA),
    FOREIGN KEY (NUMERO_CONTA) REFERENCES conta (NUMERO) ON DELETE CASCADE ON UPDATE CASCADE,
     FOREIGN KEY (SSN_CLIENTE) REFERENCES cliente (SSN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE dependente(
SSN_BANCARIO INT NOT NULL ,
NOME VARCHAR(15),
PRIMARY KEY (SSN_BANCARIO,NOME),
FOREIGN KEY (SSN_BANCARIO) REFERENCES bancario (SSN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE emprestimo(
NUMERO INT NOT NULL,
MONTANTE DECIMAL(15,2),
NUMERO_AGENCIA INT ,
SSN_CLIENTE INT ,
PRIMARY KEY (NUMERO),
FOREIGN KEY (NUMERO_AGENCIA) REFERENCES agencia (NUMERO) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY (SSN_CLIENTE) REFERENCES cliente (SSN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE pagamento(
NUMERO_PAGAMENTO INT NOT NULL,
NUMERO_EMPRESTIMO INT NOT NULL,
MONTANTE DECIMAL(15,2),
DIA DATE,
PRIMARY KEY (NUMERO_PAGAMENTO,NUMERO_EMPRESTIMO),
FOREIGN KEY(NUMERO_EMPRESTIMO) REFERENCES emprestimo(NUMERO) ON DELETE CASCADE ON UPDATE CASCADE
);

