CREATE DATABASE empresa;
CREATE TABLE empresa.Empregado
(
PNOME VARCHAR(15) NOT NULL,
MINICIAL CHAR,
UNOME VARCHAR(15)   , 
SSN BIGINT NOT NULL   ,
DATANASC DATE ,
DENDERECO VARCHAR (80),
SEXO BIT ,
SALARIO DECIMAL(10,2),
SSN_SUPERVISOR BIGINT NOT NULL DEFAULT 1,
DNUMERO_DEPARTAMENTO INTEGER   ,

PRIMARY KEY (SSN),
FOREIGN KEY (SSN_SUPERVISOR) REFERENCES empresa.Empregado (SSN)  ON DELETE SET  DEFAULT ON UPDATE CASCADE
);
 
INSERT empresa.Empregado(PNOME,SSN) VALUES ('GERENTE_PADRAO',1);

CREATE TABLE empresa.Departamento(
DNOME VARCHAR(15),
DNUMERO INTEGER NOT NULL ,
SSN_EMPREGADO BIGINT NOT NULL DEFAULT 1  ,
DATAINICIO DATE ,

PRIMARY KEY (DNUMERO),
FOREIGN KEY (SSN_EMPREGADO) REFERENCES empresa.Empregado (SSN) ON DELETE DEFAULT ON UPDATE CASCADE 
);  


ALTER TABLE empresa.Empregado ADD FOREIGN KEY(DNUMERO_DEPARTAMENTO) REFERENCES empresa.Departamento(DNUMERO) ON DELETE RESTRICT ON UPDATE CASCADE;
 
CREATE TABLE empresa.Projeto (
PNOME VARCHAR(15),
PNUMERO  INTEGER NOT NULL ,
PLOCALIZACAO VARCHAR(20),
DNUMERO_DEPARTAMENTO INTEGER NOT NULL,

PRIMARY KEY (PNUMERO),
FOREIGN KEY (DNUMERO_DEPARTAMENTO) REFERENCES empresa.Departamento (DNUMERO)
);

CREATE TABLE empresa.Dependente(
SSN_EMPREGADO BIGINT NOT NULL ,
NOME_DEPENDENTE VARCHAR(15) ,
SEXO BIT ,
DATANASC DATE NOT NULL ,
PARENTESCO VARCHAR(15) NOT NULL,

PRIMARY KEY(SSN_EMPREGADO,NOME_DEPENDENTE),
FOREIGN KEY (SSN_EMPREGADO) REFERENCES empresa.Empregado (SSN)
);

CREATE TABLE empresa.Deptolocais(
LNUMERO BIGINT NOT NULL ,
DLOCALIZACAO VARCHAR(15) NOT NULL,
DNUMERO_DEPARTAMENTO INTEGER NOT NULL ,

PRIMARY KEY (LNUMERO),
FOREIGN KEY (DNUMERO_DEPARTAMENTO) REFERENCES empresa.Departamento (DNUMERO)
);

CREATE TABLE empresa.trabalhaem(
SSN_EMPREGADO BIGINT NOT NULL,
PNUMERO_PROJETO INTEGER NOT NULL ,
HORAS TIME ,

PRIMARY KEY (SSN_EMPREGADO,PNUMERO_PROJETO),
FOREIGN KEY (SSN_EMPREGADO) REFERENCES empresa.Empregado (SSN) ,
FOREIGN KEY (PNUMERO_PROJETO) REFERENCES empresa.Projeto (PNUMERO)
);

