DROP DATABASE IF EXISTS bd;
CREATE DATABASE bd;
USE bd;

CREATE TABLE empregado(
PNOME VARCHAR(20) NOT NULL,
MINICIAL CHAR,
UNOME VARCHAR(20),
SSN BIGINT NOT NULL,
DATANASC DATE ,
ENDERECO VARCHAR(80),
SEXO BIT , 
SALARIO DECIMAL(10,2),
SSN_SUPERVISOR  BIGINT ,

PRIMARY KEY (SSN),
FOREIGN KEY (SSN_SUPERVISOR) REFERENCES empregado(SSN) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE departamento(
DNOME VARCHAR (20) NOT NULL,
DNUMERO BIGINT  NOT NULL , 
SSN_EMPREGADO BIGINT ,
DATAINICIO DATE ,

PRIMARY KEY (DNUMERO),
FOREIGN KEY (SSN_EMPREGADO) REFERENCES empregado (SSN) ON DELETE SET NULL ON UPDATE CASCADE
);

ALTER TABLE empregado ADD DNUMERO_DEPARTAMENTO BIGINT ;
ALTER TABLE empregado ADD FOREIGN KEY(DNUMERO_DEPARTAMENTO) REFERENCES departamento(DNUMERO) ON DELETE SET NULL ON UPDATE CASCADE ;

CREATE TABLE projeto (
PNOME VARCHAR (20) NOT NULL,
PNUMERO BIGINT NOT NULL,
PLOCAL VARCHAR(80) NOT NULL,
DNUMERO_DEPARTAMENTO BIGINT ,

PRIMARY KEY (PNUMERO),
FOREIGN KEY (DNUMERO_DEPARTAMENTO) REFERENCES departamento (DNUMERO) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE dependente(
SSN_EMPREGADO BIGINT NOT NULL ,
NOME_DEPENDENTE VARCHAR (20) NOT NULL,
SEXO BIT ,
DATANASC DATE ,
PARENTESCO VARCHAR (20),

PRIMARY KEY(SSN_EMPREGADO,NOME_DEPENDENTE),
FOREIGN KEY (SSN_EMPREGADO) REFERENCES empregado(SSN) ON DELETE CASCADE ON UPDATE CASCADE 
);

CREATE TABLE deptolocalizacoes(
LNUMERO INT NOT NULL,
DLOCAL VARCHAR(20) NOT NULL,
DNUMERO_DEPARTAMENTO BIGINT,
PRIMARY KEY (LNUMERO),
FOREIGN KEY (DNUMERO_DEPARTAMENTO) REFERENCES departamento (DNUMERO) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE trabalha_em (
SSN_EMPREGADO BIGINT ,
PNUMERO_PROJETO BIGINT,
HORAS DECIMAL(4,2),

PRIMARY KEY(SSN_EMPREGADO,PNUMERO_PROJETO),
FOREIGN KEY (SSN_EMPREGADO) REFERENCES empregado (SSN) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (PNUMERO_PROJETO) REFERENCES  projeto (PNUMERO) ON UPDATE CASCADE ON DELETE  CASCADE
);

